export const chataData = [
    {
        id: 1,
        lastName: "Doe",
        firstName: "John",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
      {
        id: 2,
        lastName: "Doe",
        firstName: "Jane",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
      {
        id: 3,
        lastName: "Doe",
        firstName: "Alice",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
      {
        id: 4,
        lastName: "Doe",
        firstName: "Bob",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },{
        id: 1,
        lastName: "Doe",
        firstName: "John",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
      {
        id: 2,
        lastName: "Doe",
        firstName: "Jane",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
      {
        id: 3,
        lastName: "Doe",
        firstName: "Alice",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
      {
        id: 4,
        lastName: "Doe",
        firstName: "Bob",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },{
        id: 1,
        lastName: "Doe",
        firstName: "John",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
      {
        id: 2,
        lastName: "Doe",
        firstName: "Jane",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
      {
        id: 3,
        lastName: "Doe",
        firstName: "Alice",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
      {
        id: 4,
        lastName: "Doe",
        firstName: "Bob",
        lastMessage: "Hello World",
        createdAt: "2021-09-01T12:00:00Z",
        unreadMessages: 3,
        profilePicture: "../../assets/images/jerusalem.jpeg",
      },
];
